services:
    apache:
      image: 'ubuntu/apache2:2.4-22.04_beta'
      env_file:
        - ./env/apache.env
      ports:
        - '8080:80'
      volumes:
        - ./linux/etc/apache2:/etc/apache2
        - ./linux/usr/lib/apache2:/usr/lib/apache2
        - ./linux/var/www/html:/var/www/html
      depends_on:
        - php

    php:
      build:
        context: dockerfiles
        dockerfile: php.dockerfile
      volumes:
        - ./linux/var/www/html:/var/www/html
        - ./linux/usr/lib/apache2:/usr/lib/apache2
      ports:
        - '9000:9000'
      depends_on:
        - mysql

    mysql:
      image: mysql:8.0.31-debian
      env_file:
        - ./env/mysql.env
      volumes:
        - ./linux/var/lib/mysql:/var/lib/mysql
      ports:
        - '3309:3306'

    composer:
      build: 
        context: dockerfiles
        dockerfile: composer.dockerfile
      volumes:
        - ./linux/var/www/html:/var/www/html

    artisan:
      build:
        context: dockerfiles
        dockerfile: php.dockerfile
      volumes:
        - ./linux/var/www/html:/var/www/html
      entrypoint: ["php", "/var/www/html/laravel-app/artisan"]

    npm:
      image: node:18.12.1-alpine
      working_dir: /var/www/html/laravel-app
      entrypoint: ["npm"]
      volumes:
        - ./linux/var/www/html:/var/www/html

    
# ----- Apache php -----------------------------------------------------
# sudo docker-compose up -d
# sudo docker-composesudo docker-compose down
# sudo docker cp apache_server_1:/etc/apache2 /home/foxcodenine/foxfiles/Projects/Docker_and_kubernetes_The_practical_guild_2022/my_try/apache
# sudo docker cp apache_server_1:/ /home/foxcodenine/foxfiles/Projects/Docker_and_kubernetes_The_practical_guild_2022/my_try/apache/root

# ----- Running --------------------------------------------------------
# sudo docker-compose up -d --build apache

# ----- Composer --------------------------------------------------------

# sudo docker-compose run --rm composer create-project laravel/laravel laravel-app
# sudo docker-compose run --rm composer require laravel/ui --dev -d ./laravel-app




# ----- Artisan ----------------------------------------s----------------

# sudo docker-compose run --rm artisan migrate

# sudo docker-compose run --rm artisan ui vue --auth

# sudo docker-compose run --rm artisan route:list




# php artisan ui vue --auth

# sudo docker-compose run --rm artisan make:model Robot --migration


# ----- Mysql ----------------------------------------------------------
# docker exec -it laravel_mysql_1 bash -l

# ----- NPM ------------------------------------------------------------
# sudo docker-compose run --rm npm install --force
# sudo docker-compose run --rm npm run dev



# sites:
#   https://www.digitalocean.com/community/tutorials/how-to-install-and-set-up-laravel-with-docker-compose-on-ubuntu-22-04
#   https://hub.docker.com/r/ubuntu/apache2
#   https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04#step-3-installing-php
#   https://devops.tutorials24x7.com/blog/containerize-php-with-apache-mysql-and-mongodb-using-docker-containers