"""empty message

Revision ID: cba06fd2cba1
Revises: 86a5d4c4792a
Create Date: 2020-02-27 14:19:21.752956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cba06fd2cba1'
down_revision = '86a5d4c4792a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('followee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('follower', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followee'], ['users.id'], name='followers_ibfk_1'),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], name='followers_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
