"""empty message

Revision ID: b898a0fea851
Revises: 55fcbf9329c6
Create Date: 2020-02-21 09:23:49.003477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b898a0fea851'
down_revision = '55fcbf9329c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_date')
    # ### end Alembic commands ###
