"""empty message

Revision ID: de17cb1a7f89
Revises: 7a3f8376b8aa
Create Date: 2020-02-22 09:41:22.668926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de17cb1a7f89'
down_revision = '7a3f8376b8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('tweeds','tweets')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('tweets','tweeds')
    # ### end Alembic commands ###
