"""empty message

Revision ID: 4cf3ebea1cbf
Revises: 9a1ac3d689d4
Create Date: 2019-11-28 11:36:46.472263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cf3ebea1cbf'
down_revision = '9a1ac3d689d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('order','orders',schema=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders','order',schema=None)
    # ### end Alembic commands ###
