"""empty message

Revision ID: 5309585f2837
Revises: b4e332ed2369
Create Date: 2019-11-29 10:08:46.007764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5309585f2837'
down_revision = 'b4e332ed2369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscibed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscibed')
    # ### end Alembic commands ###
