"""empty message

Revision ID: 9a1ac3d689d4
Revises: f5147f6a38d2
Create Date: 2019-11-28 11:31:40.312263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1ac3d689d4'
down_revision = 'f5147f6a38d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscribed')
    # ### end Alembic commands ###
