"""empty message

Revision ID: b16144a625f9
Revises: 4cf3ebea1cbf
Create Date: 2019-11-28 14:05:54.553231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16144a625f9'
down_revision = '4cf3ebea1cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pay', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pay')
    # ### end Alembic commands ###
