"""empty message

Revision ID: cd87ca91ac81
Revises: 6dc1a5f8c57b
Create Date: 2020-06-15 11:56:36.108272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd87ca91ac81'
down_revision = '6dc1a5f8c57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'date_created')
    # ### end Alembic commands ###
