apiVersion: v1
kind: Service
metadata: 
  name: backend
  labels:
    mygroup: example  
spec:
  selector:
    myapp: second-app
  ports:
    - protocol: 'TCP'
      port: 81
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
  # type: ClusterIP
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    mygroup: example  
spec:
  replicas: 1 
  selector:
    matchLabels:
      myapp: second-app
      mytier: backend
  template:
    metadata:
      labels:
        myapp: second-app
        mytier: backend
    spec:
      containers:
        - name: second-node
          image: foxcodenine/kub-first-app:2
        # - name: ...
        #   image: ...
