apiVersion: v1
kind: Service
metadata: 
  name: backend
  # labels:
  #   mygroup: example  
spec:
  selector:
    myapp: second-app
  ports:
    - protocol: 'TCP'
      port: 81
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
  # type: ClusterIP
  # type: NodePort



