apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: foxcodenine/kub-demo-auth:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"