apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: foxcodenine/kub-demo-tasks:latest
        env:
          - name: AUTH_ADDRESS
            # value: localhost
            # value: "10.111.57.157"           #  auth-service ClusterIP  
            value: "auth-service.default"      #  you can also use the service name & namespace since Kubernetes is Using CoreDNS for Service Discovery
          - name: TASKS_FOLDER
            value: tasks
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"