"""empty message

Revision ID: 86a5d4c4792a
Revises: 0ff8de35aad3
Create Date: 2020-02-27 13:59:16.192566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86a5d4c4792a'
down_revision = '0ff8de35aad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followee', sa.Integer(), nullable=True))
    op.add_column('followers', sa.Column('follower', sa.Integer(), nullable=True))
    op.add_column('followers', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('followers_ibfk_2', 'followers', type_='foreignkey')
    op.drop_constraint('followers_ibfk_1', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['followee'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['follower'], ['id'])
    op.drop_column('followers', 'follower_id')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('followers', sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_ibfk_1', 'followers', 'users', ['followed_id'], ['id'])
    op.create_foreign_key('followers_ibfk_2', 'followers', 'users', ['follower_id'], ['id'])
    op.drop_column('followers', 'id')
    op.drop_column('followers', 'follower')
    op.drop_column('followers', 'followee')
    # ### end Alembic commands ###
