"""empty message

Revision ID: 118650a6d0ee
Revises: 
Create Date: 2020-04-03 10:26:40.061775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118650a6d0ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('pro_name', sa.String(length=50), nullable=False),
    sa.Column('pro_price', sa.Numeric(precision=5.2), nullable=False),
    sa.Column('pro_stock', sa.Integer(), nullable=True),
    sa.Column('pro_description', sa.String(length=500), nullable=False),
    sa.Column('pro_image', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('pro_id'),
    sa.UniqueConstraint('pro_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
