"""empty message

Revision ID: 13ddbbd26d3b
Revises: c44a436e40fc
Create Date: 2020-05-13 14:22:57.217807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ddbbd26d3b'
down_revision = 'c44a436e40fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping')
    # ### end Alembic commands ###
