"""empty message

Revision ID: 18804bfa0c62
Revises: 78e69b42de49
Create Date: 2020-05-31 15:22:52.551126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18804bfa0c62'
down_revision = '78e69b42de49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reference', mysql.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
