"""empty message

Revision ID: 6c026fe92816
Revises: 3cb16f2b1b70
Create Date: 2020-05-21 18:27:01.885115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c026fe92816'
down_revision = '3cb16f2b1b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_total', sa.Numeric(precision=6.2)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_total')
    # ### end Alembic commands ###
