"""empty message

Revision ID: d36a7bf004c1
Revises: 18804bfa0c62
Create Date: 2020-05-31 15:24:01.924863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36a7bf004c1'
down_revision = '18804bfa0c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reference', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reference')
    # ### end Alembic commands ###
