"""empty message

Revision ID: 6a89170728ba
Revises: 5309585f2837
Create Date: 2019-11-29 10:13:13.505764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a89170728ba'
down_revision = '5309585f2837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'order', schema=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('order', 'orders', schema=None)
    # ### end Alembic commands ###
