apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  # volumeMode: Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce       # <~ this can be mounted as a read write volume by a single node
    # - ReadOnlyMany      # <~ mounted as a read only  volume by multiple node (not avalable option for host path)
    # - ReadWriteMany     # <~ mounted as a read write volume by multiple node (not avalable option for host path)
  hostPath:               # <~ (by defenition is define by one node)
    path: /data
    type: DirectoryOrCreate
  # --------------------------------------------------------------------
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2


  # capacity units are Ki (kibi), Mi (mebi), Gi (gibi), Ti (tebi), Pi (pebi), Ei (exbi).
