services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.2'
    container_name: concurrency_in_golang-postgres
    ports:
      - "35432:5432"
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - /srv/docker/bind-mounts/working_with_concurrency_in_golang/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    container_name: concurrency_in_golang-redis
    ports:
      - "36379:6379"
    restart: no
    volumes:
      - /srv/docker/bind-mounts/working_with_concurrency_in_golang/redis/:/data

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: concurrency_in_golang-mailhog
    ports:
      - "31025:1025"
      - "38025:8025"
    restart: no

